import type { Metadata } from "next";
import "./globals.css";
import MainLayout from "@/components/main-layout";
import React from "react";
import { DefaultToastOptions, Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const toastOptions: DefaultToastOptions = {
  style: {
    color: "white",
    borderRadius: "4px",
    backgroundColor: "rgb(29 155 240)",
  },
  success: { duration: 4000 },
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div id="modal">{modal}</div>
        <MainLayout>{children}</MainLayout>
        <Toaster toastOptions={toastOptions} />
      </body>
    </html>
  );
}
