import type { Metadata } from "next";
import "./globals.css";
import MainLayout from "@/components/main-layout";
import React from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div id="modal">{modal}</div>
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  );
}
